export { default as Splash } from './Splash/Splash'
export { default as Make } from './Make/Make'
export { default as Model } from './Model/Model'
export { default as Year } from './Year/Year'
export { default as MyCar } from './MyCar/MyCar'
export { default as Mileage } from './Mileage/Mileage'
export { default as Month } from './Month/Month'
export { default as FooterTabs } from './FooterTabs/FooterTabs'